### ISSUE TITLE
Invalid monitor

### ISSUE THREAD

**Issue by Luwenjian888** [wavefrontshaping/slmPy#2]
I use the basic example and get this error:
Traceback (most recent call last):
File "D:\Program Files\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
self.run()
File "E:\lwj\SLM\slmpy.py", line 139, in run
frame = SLMframe(monitor = self.parent.monitor, isImageLock = self.parent.isImageLock)
File "E:\lwj\SLM\slmpy.py", line 36, in init
self.SetMonitor(monitor)
File "E:\lwj\SLM\slmpy.py", line 69, in SetMonitor
raise ValueError('Invalid monitor (monitor %d).' % monitor)
ValueError: Invalid monitor (monitor 1).

**Comment by wavefrontshaping** [comment]
Hi,

By default, it assumes you have at least two monitors and that the SLM is the second one (`monitor = 1`).
If you do not have multiple monitors (which also means you do not have an SLM?), you can test the code using the first monitor.
```
slm = slmpy.SLMdisplay(monitor = 0)
```
